server:
  address: 0.0.0.0
  port: 8081

spring:
  datasource:
    url: "jdbc:h2:mem:test"
    username: "test"
    password: "test"
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect